@startuml symbol_table

skinparam Shadowing false
skinparam ArrowColor #222
skinparam ClassBorderColor #bbb
skinparam ClassBackgroundColor white
skinparam DefaultFontName Liberation Mono
skinparam RoundCorner 8

package eu.telecomnancy.symbols {

class SymbolTable {
    + define(Symbol s)
    + Symbol resolve(String idf)
}
SymbolTable o-- "*" Symbol: - symbols:\nHashMap<Symbol>
SymbolTable --> "1" SymbolTable: - parent
SymbolTable --> "*" SymbolTable: - children

abstract class Symbol {
    + String getIdentifier()
    + Type getType()
    + Kind getKind()
}
Symbol <|-up- Variable
Symbol <|-- Procedure
Symbol <|-up- Label
Symbol -right-> "1" Kind: # kind
Symbol -left-> "1" Type: # type

class Variable {
    - String identifier
    - int offset
}

class Procedure {
    - String identifier
}
Procedure -right-> "1" SymbolTable: - blockSymbolTable
Procedure o-left-> "*" Type: - parameterTypes

class Label {
    - String identifier
    - int offset
}

enum Kind {
    PROCEDURE
    VARIABLE
    LABEL
}

enum Type {
    VOID
    INTEGER
    REAL
    STRING
}

}
' package end

@enduml